name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

  push:
    branches:
      - main
      - master

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      # 1. GitHub Overview
      - name: Generate GitHub Overview
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-overview.svg
          token: ${{ secrets.METRICS_TOKEN }}

          base: header, activity, community, repositories, metadata

          config_display: large
          config_timezone: Europe/Madrid


      # 2. Languages
      - name: Generate Languages
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-languages.svg
          token: ${{ secrets.METRICS_TOKEN }}

          base: ""

          plugin_languages: yes
          plugin_languages_limit: 6
          plugin_languages_threshold: 0%

          config_display: large
          config_timezone: Europe/Madrid


      # 3. Commit Calendar
      - name: Generate Commit Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-calendar.svg
          token: ${{ secrets.METRICS_TOKEN }}

          base: ""

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          config_display: large
          config_timezone: Europe/Madrid


      # 4. Coding Habits
      - name: Generate Coding Habits
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-habits.svg
          token: ${{ secrets.METRICS_TOKEN }}

          base: ""

          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no

          config_timezone: Europe/Madrid
