name: Generate Technologies & Tools

on:
  workflow_dispatch:

  push:
    paths:
      - "assets/technologies/*.svg"
      - "scripts/generate_technologies.py"
      - ".github/workflows/technologies.yml"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Generate Technologies & Tools SVG
        run: |
          python scripts/generate_technologies.py

      - name: Commit generated SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add assets/technologies.svg

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update technologies animation"
            git push
          fi
